# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books2_app', '0002_auto_20170524_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_print',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
